[2024-06-04T23:40:19.606+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T23:40:19.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.conectando_con_redshift manual__2024-06-04T23:40:11.728183+00:00 [queued]>
[2024-06-04T23:40:19.629+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.conectando_con_redshift manual__2024-06-04T23:40:11.728183+00:00 [queued]>
[2024-06-04T23:40:19.630+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T23:40:19.640+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conectando_con_redshift> on 2024-06-04 23:40:11.728183+00:00
[2024-06-04T23:40:19.646+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=57) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T23:40:19.648+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2024-06-04T23:40:19.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'conectando_con_redshift', 'manual__2024-06-04T23:40:11.728183+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/entregable_dag.py', '--cfg-path', '/tmp/tmphk_kt06r']
[2024-06-04T23:40:19.650+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask conectando_con_redshift
[2024-06-04T23:40:19.685+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.conectando_con_redshift manual__2024-06-04T23:40:11.728183+00:00 [running]> on host fd0d5636e48d
[2024-06-04T23:40:19.744+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Guillermo Hern√°ndez' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='conectando_con_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T23:40:11.728183+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T23:40:11.728183+00:00'
[2024-06-04T23:40:19.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T23:40:21.923+0000] {logging_mixin.py:188} INFO - Connection successfully!
[2024-06-04T23:40:22.547+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T23:40:22.548+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T23:40:22.566+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=conectando_con_redshift, run_id=manual__2024-06-04T23:40:11.728183+00:00, execution_date=20240604T234011, start_date=20240604T234019, end_date=20240604T234022
[2024-06-04T23:40:22.603+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T23:40:22.622+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-04T23:40:22.623+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
